version: 0.2

env:
  variables:
    DOCKER_HUB_USERNAME: "beomseo25"
    IMAGE_NAME: "sample-java1"
  
  # AWS Systems Manager Parameter Store 보안 금고 연동
  parameter-store:
    DOCKER_HUB_PASSWORD: "/docker/password"

phases:
  install:
    runtime-versions:
      java: corretto17 # Amazon OpenJDK 17 버전 사용
  
  pre_build:
    commands:
      - echo "[CI 준비] 환경 권한 설정 및 Docker 로그인 중..."
      - chmod +x ./gradlew
      - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

  build:
    commands:
      - echo "[CI 1단계] 소스 컴파일 및 테스트 코드를 강제 검증합니다..."
      - ./gradlew clean build 

  post_build:
    commands:
      - echo "[CI 2단계] 테스트 통과 완료! Docker 이미지 빌드 및 푸시를 시작합니다..."
      - docker build -t $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest .
      - docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest
      
      - echo "[CI 3단계] 배포 파일브라우저 확인용 실시간 업데이트 영수증을 생성합니다..."
      - echo "======================================" > version.txt
      - echo " [배포 완료] CI/CD 파이프라인 업데이트 영수증" >> version.txt
      - echo "======================================" >> version.txt
      - echo "- 배포 일시 :" $(date +'%Y-%m-%d %H:%M:%S KST') >> version.txt
      - echo "- 커밋 버전 :" $CODEBUILD_RESOLVED_SOURCE_VERSION >> version.txt
      - echo "======================================" >> version.txt
      - echo "모든 빌드 및 이미지 업로드 작업이 성공적으로 끝났습니다."

artifacts:
  files:
    - appspec.yml   
    - version.txt          
    - scripts/** 
  discard-paths: yes  
